In [ ]:
import torch

x = torch.arange(4.0)
x

: 

In [4]:
x.requires_grad_(True)
x.grad

In [5]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
torch.dot(x, x)

tensor(14., grad_fn=<DotBackward0>)

In [7]:
y.backward()

In [8]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [9]:
torch.dot(x, x)

tensor(14., grad_fn=<DotBackward0>)

In [10]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [11]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [17]:
%matplotlib inline
import math
import time
import numpy as np
import torch


In [18]:
n = 10000
a = torch.ones(n)
b = torch.ones(n)

In [19]:
class Timer:  #@save
    """记录多次运行时间"""
    def __init__(self):
        self.times = []
        self.start()

    def start(self):
        """启动计时器"""
        self.tik = time.time()

    def stop(self):
        """停止计时器并将时间记录在列表中"""
        self.times.append(time.time() - self.tik)
        return self.times[-1]

    def avg(self):
        """返回平均时间"""
        return sum(self.times) / len(self.times)

    def sum(self):
        """返回时间总和"""
        return sum(self.times)

    def cumsum(self):
        """返回累计时间"""
        return np.array(self.times).cumsum().tolist()

In [20]:
c = torch.zeros(n)
timer = Timer()
for i in range(n):
    c[i] = a[i] + b[i]
f'{timer.stop():.5f} sec'

'0.09609 sec'

In [21]:
timer.start()
d = a + b
f'{timer.stop():.5f} sec'

'0.00000 sec'

In [22]:
def normal(x, mu, sigma):
    p = 1 / math.sqrt(2 * math.pi * sigma**2)
    return p * np.exp(-0.5 / sigma**2 * (x - mu)**2)